### ISSUE TITLE
Date picker: label and placeholder shown simultaneously

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-material-theme#1]
_From @jouni on August 28, 2017 14:27_

The label and placeholder texts are shown on top of each other:
![datepicker2](https://user-images.githubusercontent.com/66382/29777852-1e94b142-8c16-11e7-9fe8-60c7b7bd84c2.gif)

The text field doesn’t have the same problem, and the placeholder text is revealed only when focused:
![textfield1](https://user-images.githubusercontent.com/66382/29777875-2f79650c-8c16-11e7-816b-802fc934eced.gif)

_Copied from original issue: vaadin/vaadin-themes#46_

**Comment by jouni** [comment]
This happens because `vaadin-date-picker` binds to the `label` property instead of the attribute: https://github.com/vaadin/vaadin-date-picker/blob/master/src/vaadin-date-picker.html#L66

@tomivirkki, can you add a new issue for date picker that would fix this?

**Comment by tomivirkki** [comment]
I don't think binding to an attribute would be the right fix for this. `label` is a property of the text-field and it's not required to be set declaratively with an attribute; `textField.label = 'Label';` is a just as valid.

The issue kind of indicates that material theme was relying on a state attribute ("label") that isn't defined. Not anymore at least. And the issue doesn't seem to occur in latest master now either so I guess this can be closed?

**Comment by jouni** [comment]
> I don't think binding to an attribute would be the right fix for this. label is a property of the text-field and it's not required to be set declaratively with an attribute; textField.label = 'Label'; is a just as valid.

Right, that’s true. But then text-field should `reflectToAttribute` the `label` property?

Valo also relies on the attribute being present: https://github.com/vaadin/vaadin-text-field/blob/master/theme/valo/vaadin-text-field.html#L46-L53

**Comment by tomivirkki** [comment]
Ok. That state attribute doesn't exist now but can be added (by reflecting the property and adding to state attributes listing) if it's needed.

**Comment by tomivirkki** [comment]
Should it be reflected in the host elements also (date-picker, combo-box, dropdown-menu...)?

**Comment by tomivirkki** [comment]
https://github.com/vaadin/vaadin-text-field/issues/186

**Comment by jouni** [comment]
> Should it be reflected in the host elements also (date-picker, combo-box, dropdown-menu...)?

Not for now, at least.

**Comment by jouni** [comment]
This has been fixed by the updates in vaadin-text-field and in the theme (now in master).
