### ISSUE TITLE
vaadin-grid not using theme

### ISSUE THREAD

**Issue by anantoghosh** [vaadin/vaadin-material-theme#13]
I am extremely new to vaadin elements and have been trying for hours to get vaadin-grid to use vaadin-material-theme. Other themeable components are working though.

Using polymer-cli (1.5.7), created fresh polymer-starter-kit

```html

<link rel="import" href="../bower_components/polymer/polymer-element.html">

<link rel="import" href="../bower_components/vaadin-material-theme/vaadin-grid.html">
<link rel="import" href="../bower_components/vaadin-material-theme/vaadin-button.html">
<link rel="import" href="../bower_components/vaadin-material-theme/vaadin-checkbox.html">
<link rel="import" href="../bower_components/vaadin-material-theme/vaadin-text-field.html">

<link rel="import" href="../bower_components/vaadin-button/vaadin-button.html">
<link rel="import" href="../bower_components/vaadin-checkbox/vaadin-checkbox.html">
<link rel="import" href="../bower_components/vaadin-text-field/vaadin-text-field.html">

<link rel="import" href="../bower_components/vaadin-grid/vaadin-grid-column.html">
<link rel="import" href="../bower_components/vaadin-grid/vaadin-grid-selection-column.html">
<link rel="import" href="../bower_components/vaadin-grid/vaadin-grid.html">

<dom-module id="my-view1">
  <template>
    <style include="">
      :host {
        display: block;

        padding: 10px;
      }

    </style>

    <vaadin-checkbox></vaadin-checkbox>
    <vaadin-text-field></vaadin-text-field>
    <vaadin-button>Button</vaadin-button>

    <vaadin-grid items="[[items]]">
      <vaadin-grid-selection-column auto-select> </vaadin-grid-selection-column>
      <vaadin-grid-column>
        <template class="header">Name</template>
        <template>[[item.firstName]]</template>
      </vaadin-grid-column>
    </vaadin-grid>

  </template>

  <script>
    class MyView1 extends Polymer.Element {
      static get is() { return 'my-view1'; }

      static get properties() {
        return {
          items: Array
        }
      }

      ready() {
        super.ready();
        var items = [];
        for (var i = 0; i < 10; i++) {
          items.push({ firstName: 'First Name ' + i, lastName: 'Last Name ' + i });
        }
        this.items = items;
      }
    }

    window.customElements.define(MyView1.is, MyView1);
  </script>
</dom-module>

```
The checkbox, input and button get styled correctly.
But styles are not applied to the grid.
![vaadin](https://user-images.githubusercontent.com/12339068/32136721-60363cc0-bc30-11e7-9764-3326d339e6f3.PNG)

![vaadin2](https://user-images.githubusercontent.com/12339068/32136843-1d5bde52-bc33-11e7-9684-14077ef75902.PNG)

The file is fetched
![vaadin3](https://user-images.githubusercontent.com/12339068/32136879-ec876d68-bc33-11e7-9791-2fced346a91a.PNG)

(Testing on Chrome 62)
Any help?

**Comment by platosha** [comment]
Please check your installed version of `<vaadin-grid>`: `$ bower list | grep vaadin-grid`. Themes support was introduced in `v4.0.0-alpha1`.

**Comment by anantoghosh** [comment]
@platosha ah okay, i've got v3 installed.
This wasn't metioned in the docs https://vaadin.com/elements/vaadin-grid.

**Comment by jouni** [comment]
Sorry about that. The documentation around themes is still largely lacking, but we’re working on it.

Did you get a version conflict warning from Bower when you installed your dependencies? You should have, as `vaadin-material-theme` requires vaadin-grid 4.0: https://github.com/vaadin/vaadin-material-theme/blob/master/bower.json#L38

**Comment by anantoghosh** [comment]
@jouni No warnings.  
Bower won't install devDependencies when using `bower install package` right?
  
![vaadin4](https://user-images.githubusercontent.com/12339068/32172709-8b012014-bda2-11e7-9a39-cc8c3bd24397.PNG)

**Comment by jouni** [comment]
Ah, of course. Sorry, my mistake 🤦‍♂️

Now I’m not sure how to set up the dependencies. The theme supports a certain version of an element, but doesn’t necessarily require it, as someone can be using the theme just for some other element. Not sure how bad it would be to have all of the elements in the dependencies, and just have everyone download all the elements.

The other option I now see is to somehow clearly indicate that you should check the `devDepencencies` manually to see what versions you should be using.

**Comment by anantoghosh** [comment]
Yeah I understand, bower can't handle optional dependencies like this.  
Forcing elements to be installed with dependencies may lead to conflict issues.  
Maybe it would be more obvious if the themes and elements shared the same major version number, but it is something your team needs to discuss.   
Still, I think it's better mentioning compatibility in documentation.  

Hopefully, polymer 3 with yarn will solve these problems.  
Thanks for your help @jouni
