### ISSUE TITLE
Documentation has link to non-existing page

### ISSUE THREAD

**Issue by vaadin-kim** [vaadin/vaadin-material-theme#14]
https://cdn.vaadin.com/vaadin-material-theme/0.3.0/demo/grids.html

Under "Styling API", there is a link to customization instructions which points to https://cdn.vaadin.com/vaadin-material-theme/0.3.0/demo/customization.html but the page does not exist.

**Comment by vicsstar** [comment]
Hi @vaadin-kim! We will fix this as soon as possible.

Regards,

**Comment by jouni** [comment]
The link seems to be fixed now. Not sure when or how, though.

**Comment by web-padawan** [comment]
Fixed in 1174ee1
