### ISSUE TITLE
Styling of the underline

### ISSUE THREAD

**Issue by xelra** [vaadin/vaadin-material-theme#18]
I've been noticing that in the vaadin input elements `vaadin-date-picker` and `vaadin-text-input` the underline isn't styled correctly.

This issue affects padding in all states (hover, focus, unfocused) as well as the underline itself.

Before writing this issue, I've been reading the Material Design spec very closely and noticed that there are contradictions in the animations and illustrations they show. 

Here is a correct illustration taken from the spec:
![input-redline](https://user-images.githubusercontent.com/908568/34445756-2d08781e-ecd6-11e7-8c27-946d95877f6f.png)
What can be seen from this picture is that the 8dp padding are supposed to go to the baseline of the underline.
In all the spacing numbers they provide, the underline does not have a size. Spacing is always meant towards the baseline of the underline. In other words, the underline is inset.

In the specs they also have this image:
![placeholder-redline](https://user-images.githubusercontent.com/908568/34445868-f149fe5a-ecd6-11e7-8c62-dc22f4472969.png)
But this is wrong. It doesn't go together with all the information they provide. The 8dp padding should still go to the baseline. 

This means that in the unfocused state, the "visual" padding between the text and the underline is 7dp and the thickness of the underline is 1dp, adding up to 8dp to the baseline.

And in the hover and focused state, the "visual" padding between the text and the underline is 6dp and the thickness of the underline is 2 dp, adding up to 8 dp to the baseline.

So when the underline "thickens", it will appear as if it would "thicken" towards the top. 

Right now in `vaadin-date-picker` and `vaadin-text-input`, there's a constant 8px padding between the input and the underline and the underline appears to be "thickening" towards the bottom.

Please have a look at this implementation of React components, where this behavior is correctly implemented: https://material-ui-next.com/demos/text-fields/

EDIT:
This picture is the best in giving a correct overview of the spacing:
![nondense](https://user-images.githubusercontent.com/908568/34450164-9d59efae-ed02-11e7-98a7-ab7b24a2c060.png)

Here is a quote from the spec about the insetting of the underline (for the hover state):
> Label text
> 
> Type: Roboto 16sp
> Color: 54% black (4.5:1 contrast ratio)
> Spacing: 8dp bottom padding, inset with bottom line

Thinking the spec through logically, the one position-fixed line in the design is the baseline of the underline.

**Comment by jouni** [comment]
Thanks for the detailed info! It seems pretty clear that the underline should be inset and contained within the 8dp padding.

Would you be willing to make a PR for this?

**Comment by jouni** [comment]
The updated [Material Design specs](https://material.io/design/components/text-fields.html) no longer have this style of a text field (only the filled and outlined styles).

Because of that, I’m closing this issue as it’s not a high priority to fix anymore. That said, the underline has been fixed to grow upwards into the field (now in master).
