### ISSUE TITLE
Focus ring around cells on refocusing window with mouse

### ISSUE THREAD

**Issue by xelra** [vaadin/vaadin-material-theme#24]
When refocusing the window with the mouse, the focus ring around cells shows.

![image](https://user-images.githubusercontent.com/908568/34955090-3d8facfc-fa23-11e7-8fd3-f675a03c3732.png)

These 3 lines are responsible for it:
https://github.com/vaadin/vaadin-material-theme/blob/master/vaadin-grid.html#L110-L112

**Comment by xelra** [comment]
My guess is that this issue comes from the `navigating` attribute being set on the `vaadin-grid` when refocusing the window.

**Comment by jouni** [comment]
This is an issue in [vaadin-grid](https://github.com/vaadin/vaadin-grid), rather than in the theme. Please reopen there if you still think this is relevant.
