### ISSUE TITLE
vaadin-item.html misses a closing bracket

### ISSUE THREAD

**Issue by feuerste** [vaadin/vaadin-material-theme#29]
In https://github.com/vaadin/vaadin-material-theme/blob/646eec6174c6aa42d96cb0d4eadd8a115ce1df60/vaadin-item.html#L2
the closing bracket is missing. This leads to parsing errors when minifying the file. Can you please add it?
Thanks!
Marco

**Comment by web-padawan** [comment]
Thank you for reporting! Fixed in 0ccc2de
