### ISSUE TITLE
vaadin-combo-box with label and placeholder are not displayed correctly when the material design is applied.

### ISSUE THREAD

**Issue by caribouflex** [vaadin/vaadin-material-theme#33]
### Description

The `vaadin-combo-box`'s label and placeholder are one over the other when the material design custom style is applied.

![image](https://user-images.githubusercontent.com/25315380/37348491-9077d7d8-26aa-11e8-8b41-acaf491125e7.png)

### Expected outcome

1. The `vaadin-combo-box` label is display and when we click the `vaadin-combo-box` label go on top and the placeholder appear.
2. The `vaadin-combo-box` label is fixed on top when there is a placeholder.

### Actual outcome

The placeholder and the label are one over the other

### Steps to reproduce

1. Put a `vaadin-combo-box` element in the page.
2. Put a `vaadin-text-field` element in the page.
3. Add the vaadin-text-field material design theme.
4. Open the page in a web browser.
5. See the bug

```
<link rel="import" href="../bower_components/vaadin-material-theme/vaadin-text-field.html">
<link rel="import" href="../bower_components/vaadin-combo-box/vaadin-combo-box.html">
<link rel="import" href="../bower_components/vaadin-text-field/vaadin-text-field.html">

<vaadin-combo-box label="City" placeholder="Enter or Choose a City" items="{{cities}}"></vaadin-combo-box>
<vaadin-text-field label="City" placeholder="Enter a City"></vaadin-text-field>
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- (Can't test) Safari 
- [x] Edge
- [x] IE 11
- (Can't test) iOS Safari
- (Can't test) Android Chrome

Issue open first in vaadin-combo-box [#586](https://github.com/vaadin/vaadin-combo-box/issues/586)

**Comment by macjuan** [comment]
Thanks a lot for reporting this issue. We have identified many issues with material-theme so please be patient with us if we do not get to this issue you reported soon enough.

**Comment by jouni** [comment]
This is fixed in master. Tested using the latest vaadin-combo-box version (4.0.1)
