### ISSUE TITLE
vaadin-grid: checkbox ripple is clipped when inside Polymer element

### ISSUE THREAD

**Issue by Jaytn** [vaadin/vaadin-material-theme#34]
I hope this is the right place and I'm not missing something obvious here.

### Description
When using a `vaadin-grid` with  `vaadin-material-theme` inside a Polymer element, the ripple effect on a checkbox is not shown correctly (clipped to a rectangle).
The ripple displays correctly when _not_ inside a Polymer element

### Expected outcome
![image](https://user-images.githubusercontent.com/6250290/37556035-a79de95e-29f0-11e8-99b7-25a632ec8184.png)

### Actual outcome
![image](https://user-images.githubusercontent.com/6250290/37556047-bd74f2d6-29f0-11e8-81d2-84f25896aa36.png)

### Steps to reproduce
- make a new Polymer element
- place `vaadin-grid` inside the element
- use a checkbox for selection in the grid (eg `vaadin-grid-selection-column`)
- use `vaadin-material-theme` on the `vaadin-grid`
- use the Polymer element
- click on the checkbox
- ???
- profit

Or just:
- Look at [this handy JSFiddle](https://jsfiddle.net/cjnwzq2d/9/)

### Notes
- I've only tested this in Chrome with
`polymer#2.5.0` && ( `vaadin-grid#4.1.7` || `vaadin-grid#4.0.0` ) &&  `vaadin-material-theme#0.3.0`. 
- The bug works with any way to put in a Material checkbox, 
whether putting it in via `vaadin-grid-selection-column` or manually in a `vaadin-grid-column`,
 with either `vaadin-checkbox` or `paper-checkbox`
- I've managed to show the ripple by manually setting a `margin: 15px;` on the `paper-checkbox`, but that screws with the row-height, and I don't think this is intended to be necessary
- Please don't yell at me if I'm just too stupid to use your element correctly 🙂

**Comment by macjuan** [comment]
We do not yell. Thanks for good reporting of this issue. There is currently multiple issues with overall material theme so please be patient until we get into this.

**Comment by jouni** [comment]
This is now fixed in 0.4.0.

**Comment by jouni** [comment]
Here’s an updated jsfiddle: https://jsfiddle.net/05Lwzwdz/
