### ISSUE TITLE
Could not find style data in module named vaadin-date-picker-overlay-default-theme

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-material-theme#35]
_From @pdesjardins90 on April 16, 2018 21:0_

### Description
I get this warning using:
- vaadin-material-theme (0.3.0)
- vaadin-date-picker (v3.0.0-beta5)

`Could not find style data in module named vaadin-date-picker-overlay-default-theme`

_Copied from original issue: vaadin/vaadin-date-picker#537_

**Comment by web-padawan** [comment]
_From @pdesjardins90 on April 16, 2018 21:2_

Culprit is in vaadin-material-theme/vaadin-date-picker.html, line 134-136: 
```html
<dom-module id="material-date-picker-overlay" theme-for="vaadin-date-picker-overlay">
  <template>
    <style include="vaadin-date-picker-overlay-default-theme">
...
```

**Comment by web-padawan** [comment]
Thanks for the issue. The Material theme has not yet been updated to match the latest component versions, and is likely to be postponed. The team effort is currently focused on going Polymer 2 stable, and preparing Polymer 3 versions at the same time. Sorry about the mess there in Material theme, some work has been done in vaadin/vaadin-material-theme#32 but that does not include date-picker.

In the meanwhile, you should use `vaadin-date-picker` v2.0.7 which is currently the latest stable having default theme implemented (and expected to work with Material theme).

**Comment by jouni** [comment]
Fixed in bbf5879002b2f61a9f3fa65ebbc86c67d2ae8c99

**Comment by tomalec** [comment]
Given [`vaadin-date-picker@3.0.0`](https://github.com/vaadin/vaadin-date-picker/releases/tag/v3.0.0) seems to be stable release now, when this change will be released?

**Comment by jouni** [comment]
We are currently working on getting the Material theme to alpha quality for all Vaadin themes. The expectation at the moment is that we will cut a new 0.x release next week.

If you’re eager, you can always install the master branch directly with Bower.

**Comment by jouni** [comment]
Right. Looks like you are importing both `vaadin-date-picker/vaadin-date-picker.html` as well as `vaadin-material-theme/vaadin-date-picker.html`.

You should only import the latter one. The first one is the default import, which also imports the Lumo theme, so you get two themes at once conflicting.

We need to update the instructions regarding this, haven’t gotten there yet 😄

**Comment by tomalec** [comment]
> Looks like you are importing both `vaadin-date-picker/vaadin-date-picker.html` as well as `vaadin-material-theme/vaadin-date-picker.html`.

Oh. Isn't `vaadin-date-picker/vaadin-date-picker.html` a definition of the element? So should I instead of just applying a theme on top of existing element, replace the import with an actual definition?

**Comment by tomalec** [comment]
My use case is that in my app I use CustomElements/shadow roots that use `vaadin-date-picker` (and its `<link rel="import">`) in many places, deep inside.

Then, I'd like to change the theme of all of them, by setting a theme in the head of the main document (or at least the document fragment that employs all other)

**Comment by jouni** [comment]
> Isn't vaadin-date-picker/vaadin-date-picker.html a definition of the element?

No. It’s a convenient import, that transitively imports `src/vaadin-date-picker.html` (which is the actual implementation/definition of the element) and `theme/lumo/vaadin-date-picker.html` (which is the default theme).

The `vaadin-date-picker.html` file in this repo is similar, so it imports the `src/vaadin-date-picker.html` and then adds the theme.
