### ISSUE TITLE
A link in the checkbox label can't be clicked

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-material-theme#55]
![screenshot 2018-05-28 16 22 10](https://user-images.githubusercontent.com/1222264/40616341-66189534-6293-11e8-9168-dd88baaec1e9.png)

The link is clickable with the default theme (Lumo)

**Comment by jouni** [comment]
I don’t really understand what the difference is here between Lumo and Material. Tried debugging, but can’t figure it out (I even removed the `pointer-events: none;` from the theme).

**Comment by tomivirkki** [comment]
Seems to work for me after removing `pointer-events: none;` from the `[part="label"]`

**Comment by jouni** [comment]
Okay, good. I messed something up then.

There’s a comment in Lumo about the active style not working in IE11 without that, though. Need to check if that’s still the case.
