### ISSUE TITLE
date-picker is misaligned with text-fields

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-material-theme#9]
Live demo: https://jsfiddle.net/6r5htd05/36/

Expected: 
![image](https://user-images.githubusercontent.com/6059356/30424251-13cdf5c6-994e-11e7-956a-ed4e46c1e77a.png)

Actual: 
![image](https://user-images.githubusercontent.com/6059356/30424274-1ed5f504-994e-11e7-8084-0484b322f06c.png)

Chrome/Linux

**Comment by jouni** [comment]
If you add a label for the date picker, the fields align.

If you remove all labels, the fields do not align.

**Comment by jouni** [comment]
We probably need similarly “tricks” as in Valo to make fields and buttons align nicely.

**Comment by manolo** [comment]
@jouni what are those tricks ?

**Comment by jouni** [comment]
Lumo is using pseudo elements that set the baseline. Anton fixed these issues in other ways in this theme in https://github.com/vaadin/vaadin-material-theme/commit/2cb56aec947f3e31afa40fdca9bc4bff182ca4d6

Considering this issue fixed.

Here’s a test: https://cdn.vaadin.com/vaadin-material-theme/0.4.0/test/baseline.html
